### ISSUE TITLE
Create proto file for logging plugin

### ISSUE THREAD

**Issue by irsdkv** [mavlink/MAVSDK-Proto#101]
Hi all
I want to implement [LOGGING_DATA](https://mavlink.io/en/messages/common.html#LOGGING_DATA) plugin in proto.
I think that related requests should be located in own proto module `logging` ([one](https://github.com/mavlink/MAVSDK-Proto/issues/96#issuecomment-518280577) of the reasons), but may be for some reasons it should still locate in telemetry (or other existing module)?

**Comment by JonasVautherin** [comment]
Isn't it what the [`logging`](https://github.com/mavlink/MAVSDK/tree/develop/src/plugins/logging) C++ plugin does? If yes, I guess that's the way to go:

1. Create a proto file corresponding to the `logging` plugin
2. Write the gRPC code to add `logging` in `mavsdk_server`
3. Generate the language bindings

Does that make sense?

**Comment by julianoes** [comment]
Note that the logging plugin is not yet implemented, it's mostly a skeleton:
https://github.com/mavlink/MAVSDK/blob/develop/src/plugins/logging/logging.h
https://github.com/mavlink/MAVSDK/blob/develop/src/plugins/logging/logging_impl.cpp

**Comment by irsdkv** [comment]
> Isn't it what the [`logging`](https://github.com/mavlink/MAVSDK/tree/develop/src/plugins/logging) C++ plugin does?

Yes, it is.

> Note that the logging plugin is not yet implemented, it's mostly a skeleton.

Yes, I realized this an hour ago :smile: 
I think that I will try to implement it.
But, because of ULog format  looks a bit complicated, I think that I will create PR before full implementation to provide you the ability check is my understanding of logging API is correct.

**Comment by julianoes** [comment]
I could see the API to either give you a log stream or it logs directly to a file that you pass it the path to

**Comment by JonasVautherin** [comment]
If it's acceptable in terms of overhead, I believe that a stream would be a more elegant solution. And I don't know if you can "observe" a file on platforms like Android or iOS.

**Comment by julianoes** [comment]
I'm not sure if you want to stream at 20..50 kB/s through gRPC.

**Comment by irsdkv** [comment]
And also question:
I think that logging C++ plugin should parse messages and call callback for each received message (like [message_info_s](https://dev.px4.io/v1.9.0/en/log/ulog_file_format.html)) rather than pass raw data received in [MAVLink message](https://mavlink.io/en/messages/common.html#LOGGING_DATA).
This should reduce the load for IPC (gRPC or file raw r/w).
What are you think about it?

**Comment by irsdkv** [comment]
> I could see the API to either give you a log stream or it logs directly to a file that you pass it the path to

May be this can be one of ways to do it. But this solution (raw data write) really seems not suitable for gRPC

**Comment by irsdkv** [comment]
> If it's acceptable in terms of overhead, I believe that a stream would be a more elegant API. And I don't know if you can "observe" a file on platforms like Android or iOS.

I know that Android support sockets (on mobile apps this is dirty hack, but that possible). 
May be one of the solution may be in write some plugin (external for backend) which will receive messages or raw data with logging module and stream it in sockets or file?

**Comment by julianoes** [comment]
What about passing the logging plugin the path to the file or socket where it should write the log file to?

Something like this:
https://github.com/mavlink/MAVSDK/blob/e84034a468d67be6666296fadcb95312d77cc20c/src/plugins/log_files/include/plugins/log_files/log_files.h#L100-L113

**Comment by JonasVautherin** [comment]
> I'm not sure if you want to stream at 20..50 kB/s through gRPC.

I don't see why not. We get that stream from the drone through a radio, right? I believe gRPC is made to handle heavy loads on servers over the Internet.

**Comment by julianoes** [comment]
I suppose you're right.

**Comment by JonasVautherin** [comment]
I mean, that's something to try probably. My concern is just that if we write it to a file, then it may become a plugin to download the logfiles and not a plugin to stream the logs.

**Comment by julianoes** [comment]
> My concern is just that if we write it to a file, then it may become a plugin to download the logfiles and not a plugin to stream the logs.

No, you can only stream the logfile while flying, you can't download an existing logfile.

**Comment by JonasVautherin** [comment]
Right. But in terms of API, if you give me a URL to a file and I can't "observe" it, then it looks like an incomplete log file, right?

And if I can observe it, then it's more looking like IPC. If it's just about performance, I would first try to stream it over gRPC. In other words I wouldn't assume gRPC can't deal with that.

**Comment by julianoes** [comment]
I'm fine with both.

**Comment by gulyvz** [comment]
I want to list Log File and also i want to implement logging proto for MAVSDK-Python client. 

>     1. Create a proto file corresponding to the `logging` plugin
> 
>     2. Write the gRPC code to add `logging` in `mavsdk_server`
> 
>     3. Generate the language bindings
> 

Is this still the recommended way?

**Comment by JonasVautherin** [comment]
Yes, together with "Note that the logging plugin is not yet implemented, it's mostly a skeleton", meaning that you may want to have a look at the existing C++ implementation, too :smile:.

**Comment by irsdkv** [comment]
@gulyvz also may be this implementation can help you a little: https://github.com/mavlink/qgroundcontrol/blob/2f5324fd1745aa7ffa8ab1d477e2c8f1cad61c1c/src/Vehicle/MAVLinkLogManager.h

**Comment by gulyvz** [comment]
@JonasVautherin, @irsdkv thanks for your reply. I will check them all :)
