### ISSUE TITLE
Is it a drone, a system, a vehicle, a robot?

### ISSUE THREAD

**Issue by JonasVautherin** [mavlink/MAVSDK-Proto#104]
@julianoes suggests replacing `drone` by `system`, `vehicle` or `robot`. He said in a PR:

> I'm not sold on using the word drone because it can also be a plane or a rover or whatnot. On the C++ side this is called a system.

My opinion is that anyway, it is used once in the code, to instantiate the main object, and the user can choose another name there. For instance:

```python
drone = Drone()
```

or

```python
rover = Drone()
```

An argument for `System` is that it doesn't have to be a vehicle, and it could be just a gimbal. My opinion is that `System` is too generic and doesn't mean anything (like `Object` or `Thing`). `Drone` is maybe not always technically correct (e.g. it may be a bit weird to write `gimbal = Drone()`), but most of the time it is perfectly fine. Vehicle is slightly more general, but doesn't solve `gimbal = Vehicle()` either.

Note that I'm biased towards `Drone()` because it's already written in Python, Java and Swift, and therefore I wouldn't need to rename all the code and examples :see_no_evil:. I can rename everything if necessary, but then we should stick to it, trying to move towards a 1.0 release.

**Comment by JonasVautherin** [comment]
@hamishwillee: FYI

**Comment by hamishwillee** [comment]
I'm sure we can come up with even more options just from our recent experience - UAV, UAS .... :-)

FWIW I would have called it system. That is what MAVLink calls it, exactly because it could be any kind of thing on a MAVLink network.
And to counter your argument, had you named it system, then people could have called it `drone` just once to identify the real type:
```
drone = System()
```

**Comment by JonasVautherin** [comment]
> FWIW I would have called it system.

Ok, then that's two of you against me, it should be `System` :wink:. I'll update that ASAP.

**Comment by hamishwillee** [comment]
Yee har. You can still call the item drone :-)
```
drone = System()
```
