### ISSUE TITLE
More explanation in the pb_plugins README

### ISSUE THREAD

**Issue by EivindYN** [mavlink/MAVSDK-Proto#125]
After installing everything needed, there is no more explanation on how to go further. "How to use it" contains commands, but not where to use the commands. More explanation to help newcomers would be really appreciated!

**Comment by JonasVautherin** [comment]
What is it that you are trying to do? `pb_plugins` is not really for newcomers, I would say (though you're right, it could be better documented). Are you trying to use MAVSDK?

**Comment by EivindYN** [comment]
Yes I was trying to use MAVSDK-CSharp, Python or C++. Anyone of them, but CSharp og Python relies on pb_plugins so I wasn't able to. I haven't looked at setting up MAVSDK with C++ though.

**Comment by JonasVautherin** [comment]
In that case, you should not care about `pb_plugins`.

For C++, you should look at the documentation on [mavsdk.io](https://mavsdk.mavlink.io/develop/en/cpp/).

For Python, you should follow the documentation in [MAVSDK-Python](https://github.com/mavlink/mavsdk-python). The easiest way is `$ pip install mavsdk`. I wrote two blog posts to help getting started with Python, the first one being [here](https://auterion.com/getting-started-with-mavsdk-python/).

C# is not completely finished but worth trying. We have a small example project [here](https://github.com/mavlink/MAVSDK-CSharp/tree/master/MAVSDK-CSharp/MAVSDK.CSharp.ConsoleClient), if you want to try it.

In case you are interested in Java, I recently wrote a blog post to [get started with MAVSDK-Java](https://auterion.com/getting-started-with-mavsdk-java/).
