### ISSUE TITLE
> I am still having troubles about the C++ files generation. Also how do I proceed from there ?

### ISSUE THREAD

**Issue by AldoCF96** [mavlink/MAVSDK-Proto#160]
> I am still having troubles about the C++ files generation. Also how do I proceed from there ?

What troubles? Can we help?

_Originally posted by @julianoes in https://github.com/mavlink/MAVSDK-Proto/pull/154#issuecomment-642570246_

I run  the command to generate the C++ files, but I dont see any new files being created in plugins

**Comment by julianoes** [comment]
Sorry, I missed your Slack message. Copying in what I responded there as well:

```
git checkout develop
git pull
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_BACKEND=ON -Bbuild/default -H.
cmake --build build/default -j 8
```
And then try again:
```
tools/generate_from_protos.sh
```
