### ISSUE TITLE
The fpt.proto hasn't a primitive to upload files

### ISSUE THREAD

**Issue by emialonzo** [mavlink/MAVSDK-Proto#199]
Hi, i'm looking for a primitive to upload a file via FTP in the javaSKD.  As I did not find it I start looking for it [here](https://github.com/mavlink/MAVSDK-Proto/blob/88e2fd133d868d3557541d5047549f5dea457685/protos/ftp/ftp.proto) and it is not implemented. 

How is it possible to upload a file?

**Comment by JonasVautherin** [comment]
I don't understand the question. What is missing?

Did you try using [this](https://github.com/mavlink/MAVSDK-Proto/blob/88e2fd133d868d3557541d5047549f5dea457685/protos/ftp/ftp.proto#L25-L28)? Note that the [local_file_path](https://github.com/mavlink/MAVSDK-Proto/blob/88e2fd133d868d3557541d5047549f5dea457685/protos/ftp/ftp.proto#L85) is relative to `mavsdk_server`, which is the one uploading it over MAVLink :+1:.

**Comment by julianoes** [comment]
No follow up in a long time, closing.
