### ISSUE TITLE
In which module to place the subscription.

### ISSUE THREAD

**Issue by irsdkv** [mavlink/MAVSDK-Proto#96]
At this time we are implementing [ACTUATOR_OUTPUT_STATUS](https://mavlink.io/en/messages/common.html#ACTUATOR_OUTPUT_STATUS) and [ACTUATOR_CONTROL_TARGET](https://mavlink.io/en/messages/common.html#ACTUATOR_CONTROL_TARGET) messages in Proto and Backend.
I'm interested in which proto module we should put this subscriptions - telemetry, offboard or any other?

Thanks!

**Comment by julianoes** [comment]
Hm, that's a good question. I would have said telemetry historically but now I tend towards offboard. The reason is that telemetry might get overwhelming if we keep adding everything there.

What's your opinion? What's more intuitive?

**Comment by irsdkv** [comment]
I agree that Telemetry module may get too large but I think that ACTUATOR_OUTPUT_STATUS at first sight should be located in it by get it usage more intuitive (seems that this is the closest module by purpose).

But ACTUATOR_CONTROL_TARGET can be located in Offboard for the following reasons:

- SET_ACTUATOR_CONTROL_TARGET also located in that;

- In mavlink docs we can see this description of [ATTITUDE_TARGET](https://mavlink.io/en/messages/common.html#ATTITUDE_TARGET) (I think that this also related to ACTUATOR_CONTROL_TARGET, but description of that is only cut-n-paste of SET_ACTUATOR_CONTROL_TARGET :smiley: ) : 

> **This should match the commands sent in a SET_ATTITUDE_TARGET message** if the vehicle is being controlled this way.


So I think that by simplify using SET_ACTUATOR_CONTROL_TARGET and ACTUATOR_CONTROL_TARGET, it should be located in the same module by prevent excessive include of headers and overconsistency.

**Comment by JonasVautherin** [comment]
One way to see it (not sure if it helps, though) may be: if we remove the offboard plugin, does it make sense to still have this feature, or should it be removed as well? If it makes sense only (or mostly) with the offboard plugin, it should go there.

**Comment by irsdkv** [comment]
Hm. For that matter it should be located in Telemetry. Because of it can be used for detailed data collecting for various scenarios of development and testing.

**Comment by JonasVautherin** [comment]
Well, I would say that it doesn't work in both directions. My point was that:

* If the feature F1 requires plugin P1, then F1 should be part of P1
* If F1 doesn't require P1, we cannot conclude. Maybe it should go in Telemetry, but maybe it's fine to have it in P1

The camera plugin is an example of the second case. You could use subscriptions without needing to take pictures, but we still keep them in the camera plugin because it makes sense.
